package lab1.mybatis.model;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.ID
     *
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.TITLE
     *
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.LECTURER_ID
     *
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    private Integer lecturerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    private Integer universityId;

    private Lecturer lecturer;
    private University university;

    public Lecturer getLecturer() {
        return lecturer;
    }

    public void setLecturer(Lecturer lecturer) {
        this.lecturer = lecturer;
    }

    public University getUniversity() {
        return university;
    }

    public void setUniversity(University university) {
        this.university = university;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.ID
     *
     * @return the value of PUBLIC.COURSE.ID
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.ID
     *
     * @param id the value for PUBLIC.COURSE.ID
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.TITLE
     *
     * @return the value of PUBLIC.COURSE.TITLE
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.TITLE
     *
     * @param title the value for PUBLIC.COURSE.TITLE
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.LECTURER_ID
     *
     * @return the value of PUBLIC.COURSE.LECTURER_ID
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    public Integer getLecturerId() {
        return lecturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.LECTURER_ID
     *
     * @param lecturerId the value for PUBLIC.COURSE.LECTURER_ID
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    public void setLecturerId(Integer lecturerId) {
        this.lecturerId = lecturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @return the value of PUBLIC.COURSE.UNIVERSITY_ID
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    public Integer getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @param universityId the value for PUBLIC.COURSE.UNIVERSITY_ID
     * @mbg.generated Thu May 16 21:20:44 EEST 2024
     */
    public void setUniversityId(Integer universityId) {
        this.universityId = universityId;
    }
}